org: jeffhorton
app: cogs-api
service: cogs-api
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

custom:
  tableName: 'users-table-${sls:stage}'

provider:
  name: aws
  region: eu-west-2
  deploymentMethod: direct
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource:
            - arn:aws:ses:eu-west-2:296681679694:identity/kow.c-o-g-s.org.uk
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
    environment:
      SOURCE_EMAIL: mail.kow.c-o-g-s.org.uk
      ADMIN_EMAIL: jeff@goblinoid.co.uk

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
